services:
  - type: web
    name: sap-project
    runtime: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL
        value: "True"
    startCommand: gunicorn app:app
    envVars:
      - key: DB_HOST
        value: your-mysql-host
      - key: DB_USER
        value: root
      - key: DB_PASS
        value: 1978
      - key: DB_NAME
        value: social
      - key: DB_PORT
        value: "3310"
