services:
  - type: web
    name: sap-project
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app"
    envVars:
      - key: DB_HOST
        value: localhost
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: 1978
      - key: DB_NAME
        value: social
      - key: DB_PORT
        value: 3310
